### ISSUE TITLE
CLI stuck in loop

### ISSUE THREAD

**Issue by Kevan-Y** [ycechungAI/cmd-ssg#5]
Steps to reproduce:
1. `ssgy -h`
![image](https://user-images.githubusercontent.com/58233223/133363088-2619bb82-077f-4577-8af6-5893ec8ff65e.png)

or 

1. `ssgy -i .\examples\`
![image](https://user-images.githubusercontent.com/58233223/133364482-6e5eac55-a592-4d1b-ab01-a2a2db8d780b.png)

**Comment by ycechungAI** [comment]
fixed by adding process.exit(1)
