### ISSUE TITLE
CLI option -h and --help have different output help description

### ISSUE THREAD

**Issue by Kevan-Y** [ycechungAI/cmd-ssg#7]
Steps to reproduce:
1. `ssgy -h`
![image](https://user-images.githubusercontent.com/58233223/133365366-f5745d31-4d58-4746-ae8e-f8c7c899438d.png)

and
1. `ssgy --help`
![image](https://user-images.githubusercontent.com/58233223/133365343-eca9dcbe-afbd-4449-8ff9-b13b052d2393.png)

**Comment by ycechungAI** [comment]
the -h is using commander and --help is pointing to yargs
I currently have all visual elements like this as on going work
I think i either need to move everything to commander or yargs
